spring:
  application:
    name: ${HOME_AS_SERVICE_NAME:admin-service}
  datasource:
    url: ${HOME_AS_DB_URL:jdbc:postgresql:////100.66.180.10:5432/homeservice}
    username: ${HOME_AS_DB_USERNAME:admin}
    password: ${HOME_AS_DB_PASSWORD:admin}
  jpa:
    show-sql: false