spring:
  application:
    name: ${HOME_AS_SERVICE_NAME:admin-service}
  datasource:
    url: ${HOME_AS_DB_URL:jdbc:postgresql:////20.119.98.141:5432/homeservice}
    username: ${HOME_AS_DB_USERNAME:admin}
    password: ${HOME_AS_DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false