spring:
  application:
    name: ${HOME_WH_SERVICE_NAME:warehouse-service}
  datasource:
    url: ${HOME_WH_DB_URL:jdbc:postgresql://100.66.180.10:5432/homeservice}
    username: ${HOME_WH_DB_USERNAME:admin}
    password: ${HOME_WH_DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  #server:
  #  port: 8082
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
