common:
  publicEndpoints: ${HOME_COMMON_PUBLIC_ENDPOINTS:/wms/as/v1/auth/login,/wms/as/v1/auth/refresh}
  tempKcGroupId: ${HOME_COMMON_TEMP_KC_GROUP_ID:08094824-afe2-4db0-9922-fe44b34d864a}
  minio:
    url: ${HOME_MINIO_URL:http://103.75.76.68:9100}
    accessKey: ${HOME_MINIO_ACCESS_KEY:admin}
    secretKey: ${HOME_MINIO_SECRET_KEY:minioadmin}
    bucketName: ${HOME_MINIO_BUCKET_NAME:development}
    materialImageFolderStorage: ${HOME_MINIO_FOLDER_STORAGE_FILE_MATERIAL_IMAGE:material}
    projectAttachmentsFolderStorage: ${HOME_MINIO_FOLDER_STORAGE_FILE_PROJECT_ATTACHEMNTS:project}
  keycloak:
    serverUrl: ${HOME_KEYCLOAK_URL:https://iam.vworks.com.vn}
    realm: ${HOME_KEYCLOAK_REALM:tnt}
    clientId: ${HOME_KEYCLOAK_CLIENT_ID:test-client}
    clientSecret: ${HOME_KEYCLOAK_CLIENT_SECRET:aSqkktte4wwcPrL7MfuLNxZgmU3KQqHP}
#    realm: ${LED_KEYCLOAK_REALM:dev_cuongphongled}
#    clientId: ${LED_KEYCLOAK_CLIENT_ID:app_warehouse_mngt}
#    clientSecret: ${LED_KEYCLOAK_CLIENT_SECRET:wJ09Co08eYnmFdBZOtlipUBEclZT0yyJ}
    enable: ${HOME_KEYCLOAK_ENABLE:true}
  cache:
    caffeine:
      default:
        cacheName: appCache, keycloakCache
        duration: 5
        timeUnit: MINUTES
        maxCacheSize: 10000
#  admin-service:
#    name: admin-service
#    url: http://localhost:8080/wms/as/v1

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${common.keycloak.serverUrl}/realms/${common.keycloak.realm}

#  spring:
#    servlet:
#      multipart:
#        enabled: true
#        maxFileSize: 100MB
#        maxRequest: 100MB

logging:
  level:
    com.github.benmanes.caffeine: DEBUG

