common:
  tempKcGroupId: ${LED_COMMON_TEMP_KC_GROUP_ID:08094824-afe2-4db0-9922-fe44b34d864a}
  minio:
    url: ${LED_MINIO_URL:http://103.75.76.68:9100}
    accessKey: ${LED_MINIO_ACCESS_KEY:admin}
    secretKey: ${LED_MINIO_SECRET_KEY:minioadmin}
    bucketName: ${LED_MINIO_BUCKET_NAME:development}
    materialImageFolderStorage: ${LED_MINIO_FOLDER_STORAGE_FILE_MATERIAL_IMAGE:material}
    projectAttachmentsFolderStorage: ${LED_MINIO_FOLDER_STORAGE_FILE_PROJECT_ATTACHEMNTS:project}
  keycloak:
    serverUrl: ${LED_KEYCLOAK_URL:http://103.75.76.68:8180}
    realm: ${LED_KEYCLOAK_REALM:dev_cuongphongled}
    clientId: ${LED_KEYCLOAK_CLIENT_ID:app_warehouse_mngt}
    clientSecret: ${LED_KEYCLOAK_CLIENT_SECRET:wJ09Co08eYnmFdBZOtlipUBEclZT0yyJ}
    username: ${LED_KEYCLOAK_AD_USERNAME:administrator}
    password: ${LED_KEYCLOAK_AD_PASSWORD:administrator}
    enable: ${LED_KEYCLOAK_ENABLE:true}
#  admin-service:
#    name: admin-service
#    url: http://localhost:8080/wms/as/v1

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${LED_KEYCLOAK_URL:http://103.75.76.68:8180}/realms/${LED_KEYCLOAK_REALM:dev_cuongphongled}


#  spring:
#    servlet:
#      multipart:
#        enabled: true
#        maxFileSize: 100MB
#        maxRequest: 100MB

