spring:
  profiles:
    include: ${HOME_MAIN_SERVER_PROFILES:admin-service, common, home-service}
  application:
    name: ${HOME_MAIN_SERVER_NAME:Warehouse Management System}
server:
  port: ${HOME_MAIN_SERVER_PORT:8080}